void initKeyboard(void);
void closeKeyboard(void);
void getSetCurrentDir(char const*);
int kbHit(void);
int readCh(void);
void scrollUp(void);
void scrollDown(void);
void goUp(void);
void goBack(void);
void goForward(void);
void goHome(void);
void setRootPath(char const*);
void toggleMode(void);
void openFile(void);